FROM php:8.1-fpm

ARG LARAVEL_VER
ARG APP_ROOT
ARG NODE_VER=16.14.2 # LTS
ARG UID=1000
ARG USER=laravel
ARG USER_PASSWORD=laravel

# locale
RUN apt-get update && apt-get install -y --no-install-recommends locales && locale-gen C.UTF-8 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8

# laravel required packages and etc. (procps, completion)
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends git \
    vim \
    zip \
    unzip \
    procps \
    bash-completion \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install Composer
RUN curl -sS http://getcomposer.org/installer | \
    php -- --2 --filename=composer --install-dir=/usr/bin/ \
    && composer completion bash > /etc/bash_completion.d/composer
ENV COMPOSER_HOME /home/${USER}/.composer
ENV PATH $PATH:$COMPOSER_HOME/vendor/bin
# ENV COMPOSER_ALLOW_SUPERUSER 1

# https://github.com/mlocati/docker-php-extension-installer
RUN docker-php-ext-install pdo_mysql

# install nodejs npm
RUN apt-get update && apt-get install -y --no-install-recommends npm \
    && npm install -g n \
    && n ${NODE_VER} \
    && apt purge -y nodejs npm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# add general user
RUN apt-get update && apt-get install -y --no-install-recommends sudo\
    && useradd --uid ${UID} --groups sudo ${USER} --user-group --create-home --shell /bin/bash \
    && echo ${USER}:${USER_PASSWORD} | chpasswd \
    && echo root:root | chpasswd \
    && echo "%${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ${USER}

# include bashrc, prevent composer permission error
COPY ./dotfiles/* /home/${USER}/dotfiles/
# hadolint ignore=DL4006
RUN echo '[ -f ~/dotfiles/.bashrc ] && . ~/dotfiles/.bashrc'  >> /home/${USER}/.bashrc \
    && echo '[ -f ~/dotfiles/.bash_aliases ] && . ~/dotfiles/.bash_aliases' >> /home/${USER}/.bashrc \
    && echo "test 0 -eq $(find ${APP_ROOT} -maxdepth 0 -not -user ${USER} | wc -l) \
      && sudo chown -R ${USER} ${APP_ROOT}" >> /home/${USER}/.bashrc

ENV LARAVEL_VER=${LARAVEL_VER}
ENV USER=${USER}
