version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/app/
  - source: docker/
    destination: /home/ec2-user/docker/
permissions:
  - object: /var/www/
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/docker/
    owner: ec2-user
    group: ec2-user
